# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  pull_request:
    branches: [master]

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build the image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
          docker build -t muneeb/versioning:$IMAGE_TAG -f Dockerfile-v2 .
    
  build:
    name: Create Release  
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Taking the Latest Release Tag number
        id: releaseVersion
        run: |
          owner="muneeb"
          repo="my-project"
          release_json=$(curl https://api.github.com/repos/$owner/$repo/releases)
          Release_tag=$(echo "$release_json" | jq -r '.[0].tag_name')
          echo "Release_tag: Latest Tag is : $Release_tag"
          echo ::set-output name=Release_tag::"$Release_tag"
          
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Bumping Major Index
        id: bump_version_major
        if: contains(github.event.pull_request.title, 'major')
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.releaseVersion.outputs.Release_tag }}
          version-fragment: 'major'
                    
      - name: Bumping Minor Index
        id: bump_version_minor
        if: contains(github.event.pull_request.title, 'minor')
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.releaseVersion.outputs.Release_tag }}
          version-fragment: 'feature'
          
      - name: Bumping Patch Index 
        id: bump_version_patch
        if: contains(github.event.pull_request.title, 'patch')
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.releaseVersion.outputs.Release_tag }}
          version-fragment: 'bug'
          
      - name: Create release version for bump_version_major
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          owner="muneeb"
          repo="my-project"
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             https://api.github.com/repos/$owner/$repo/releases \
            -d '{"tag_name":"${{ steps.bump_version_major.outputs.next-version }}","target_commitish":"master","name":"${{ steps.bump_version_major.outputs.next-version }}","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}'
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             https://api.github.com/repos/$owner/$repo/releases \
            -d '{"tag_name":"${{ steps.bump_version_minor.outputs.next-version }}","target_commitish":"master","name":"${{ steps.bump_version_minor.outputs.next-version }}","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}'
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             https://api.github.com/repos/$owner/$repo/releases \
            -d '{"tag_name":"${{ steps.bump_version_patch.outputs.next-version }}","target_commitish":"master","name":"${{ steps.bump_version_patch.outputs.next-version }}","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}'
